package db

var usernames = []string{
	"alice",
	"bob",
	"charlie",
	"david",
	"emma",
	"frank",
	"grace",
	"henry",
	"isabella",
	"jack",
	"karen",
	"liam",
	"mia",
	"noah",
	"olivia",
	"peter",
	"quinn",
	"rachel",
	"sam",
	"tina",
	"ursula",
	"victor",
	"will",
	"xavier",
	"yara",
	"zoe",
	"lucas",
	"nina",
	"oscar",
	"paula",
	"quentin",
	"roberto",
	"sofia",
	"tiago",
	"uma",
	"valentina",
	"wesley",
	"xenia",
	"yasmin",
	"zack",
	"cetin",
	"elif",
	"mehmet",
	"ayla",
	"fatih",
	"selin",
	"emre",
	"melis",
	"burak",
	"asli",
	"okan",
}

var titles = []string{
	"10 Tips for Staying Productive While Working From Home",
	"How to Build a Simple Web App with Go and JavaScript",
	"The Ultimate Guide to Mastering CSS Flexbox",
	"Why Learning to Code Changes the Way You Think",
	"Top 5 VS Code Extensions Every Developer Should Use",
	"Understanding APIs: A Beginner’s Guide",
	"How I Built My First Django Project from Scratch",
	"The Power of Consistency in Personal Growth",
	"Debugging Like a Pro: Tools and Techniques",
	"Exploring the Future of AI in Everyday Life",
	"How to Create Responsive Websites with Ease",
	"My Journey from Beginner to Full-Stack Developer",
	"Simple Habits That Boost Your Creativity",
	"A Step-by-Step Guide to Deploying Apps on Railway",
	"What I Learned After 100 Days of Coding",
	"The Best Free Resources to Learn Programming in 2025",
	"Building a Portfolio Website: Tips and Examples",
	"How to Stay Motivated When Learning to Code",
	"Understanding Git and GitHub for Beginners",
	"Why Side Projects Are Essential for Developers",
}
var contents = []string{
	"Learn how to stay focused and manage your time effectively when working remotely.",
	"A quick guide on building a basic web app using Go and JavaScript.",
	"An easy explanation of how CSS Flexbox works with simple examples.",
	"Discover how coding improves your problem-solving and creative thinking skills.",
	"A short list of must-have VS Code extensions for better productivity.",
	"A beginner-friendly overview of what APIs are and how they work.",
	"Steps I followed to create my first Django project from scratch.",
	"Simple ideas to stay consistent and improve yourself every day.",
	"Quick debugging tips and tools to make fixing code easier.",
	"A short look at how artificial intelligence is shaping modern life.",
	"Tips for making your websites look great on all devices.",
	"A summary of my progress and lessons from learning full-stack development.",
	"Simple daily habits that help boost creativity and focus.",
	"A short guide on how to deploy apps using the Railway platform.",
	"Key takeaways from my 100-day coding challenge experience.",
	"A list of free online resources to help you learn programming.",
	"Easy steps for building a personal portfolio website.",
	"Quick tips for staying motivated while learning to code.",
	"A simple explanation of how Git and GitHub work together.",
	"Why doing small side projects can help you grow as a developer.",
}

var tags = []string{
	"productivity",
	"webdev",
	"css",
	"mindset",
	"tools",
	"api",
	"django",
	"selfgrowth",
	"debugging",
	"ai",
	"responsive",
	"fullstack",
	"creativity",
	"deployment",
	"learning",
	"resources",
	"portfolio",
	"motivation",
	"git",
	"projects",
}

var comments = []string{
	"Great post, really helpful!",
	"I learned something new today, thanks!",
	"This was super easy to follow.",
	"Love the simplicity of your explanation.",
	"Thanks for sharing this!",
	"Very useful for beginners.",
	"I’ll definitely try this out.",
	"Awesome tips, keep it up!",
	"This made things much clearer for me.",
	"Exactly what I was looking for!",
	"Nice write-up, short and to the point.",
	"Thanks! This saved me a lot of time.",
	"I never understood this until now.",
	"Looking forward to more posts like this.",
	"Simple but very informative.",
	"Cool tutorial, appreciate the effort!",
	"This topic finally makes sense now.",
	"Good read, thank you!",
	"Helpful content, keep posting!",
	"You explained it perfectly!",
}
